package com.monsterlud.groovestock.model

enum class Genre {
    BLUES, CLASSICAL, COMEDY, COUNTRY, DISCO, ELECTRONIC,
    EXPERIMENTAL, FOLK, FUNK, GOSPEL, GRUNGE, HIPHOP, HOLIDAY,
    INDIE, JAZZ, LATIN, METAL, NEWAGE, NEWWAVE, OPERA, POP,
    PUNK, REGGAE, RHYTHMANDBLUES, ROCK, SOUL, TECHNO, VOCALIST, WORLD
}